### ISSUE TITLE
[1주차] 피드백

### ISSUE THREAD

**Issue by ujentus** [atgchan/2015_GaeKyungPu#1]
- 팀 이름은? 
-  ujentus 콜라보래이터 등록 안되어 있음 (-1)
- 출사표
  종성이 팀을 위한 목표는?
- 팀 룰 (-2)
  근태(특히 모임 약속 등)에 관련된 내용은 없네? 
  회의록 정리, 위키 정리 등에 관한 룰도 없음.
  이건 팀의 룰이라기보다, 팀내 협업의 방향에 가까운 내용이다. 지난 개경프의 예를 적극 참고할 것
- 스터디 계획 (-1)
  스터디 정리는 조금 있는데 어떤식으로 어떤 내용을 가지고 누가 발표할지 등등 내용이 전혀 없다.
- 컨셉기획서 (-3)
  -개요 부분에서 "~를 추가하자"라는 것은 기획서에 들어갈 내용이 아님.
  -재미 요소 부분에서 "실제 전쟁을 하는 것 같은~~"이런 표현을 하기 위해서는 (어떤 것이 있기 때문에 그런지..) 그에 대한 구체적인 내용이 있어야 한다. 
  "약간의 컨트롤"이라는 부분이 턴제 전략 게임과 잘 맞지 않아 보이는 요소인데.. 그에 대한 설명은?
  -게임 진행 메커니즘 부분에서 "단순하지만 고려하는 수에 따라 몰입감 있게 플레이 할 수 있다"부분은 추상적이라 더 자세하게 내용을 쓰거나 빼거나 하는게 좋다.
  "운적인 요소와 미묘한 컨트롤을 통해서도 유리한 고지를 점령할 수 있다"라는 부분이 있는데 어떻게? 다시 한번 말하지만 컨셉 기획서는 읽는 사람으로 하여금 머리속에 게임 플레이가 그려져야 한다.
  "초반에 조금 밀리더라도 후반에 충분히 역전할 수 있는 희망과 기회를 제공한다." 이건 메커니즘이 아니라 재미요소중 하나인 것 같다.
- 플레이 시나리오
  게임 메커니즘이 상세히 설명 되어야 이 부분을 자유롭게 구체적으로 서술 가능하다.

전반적으로 더 구체화 시켜야 함.

스터디 내용도 ppt보다는 위키에 정리하도록! 정 귀찮으면 slideshare같은데 올리고 위키에 링크를 걸도록. (이 스터디 내용은 내게 보여주기 위함이 아니라, 팀내 또는 팀간 공유를 위함이다. 다음에 찾아보기에도 용이하게 만드는 것이 좋다. 위키는 검색 되기 때문)

**Comment by Jsfumato** [comment]
팀 룰, 스터디 계획, 컨셉기획서 수정하였습니다

**Comment by ujentus** [comment]
잘했다 +2점.
