### ISSUE TITLE
1-G Unit Palette 구현

### ISSUE THREAD

**Issue by seokmin** [atgchan/2015_GaeKyungPu#10]
유닛 팔레트를 화면 한 쪽에 만들어서 화면에 두고 싶은 말을 골라 놓을 수 있도록 구현.

**Comment by Jsfumato** [comment]
나중에 쓸 일이 없는 기능이고 프로토타입 수준의 toggle turn 구현이 어렵지 않으니
이것 대신에 toggleturn()을 구현하는게 더 적합하지 않을까

**Comment by Jsfumato** [comment]
(+ toggleTurn() 구현함)
