### ISSUE TITLE
[2주차] 피드백

### ISSUE THREAD

**Issue by ujentus** [atgchan/2015_GaeKyungPu#37]
1. 마일스톤
2. 100% 완료되면 닫아주삼.
3. todo 형태의 이슈의 경우, 구현 완료되면 해당 커밋번호 (커밋 항목의 Copy SHA활용)를 같이 붙여넣고 닫아주면 더 좋다.
4. 마일스톤 내 세부적인 이슈는 변화무쌍~~ 한 것이니 너무 형식에 얽매이지 않아도 좋다. 만들어졌던 이슈가 없어질수도 있고, 기존의 이슈가 여러개로 쪼개어 다음 마일스톤으로 미룰수도 있고... 암튼 최대한 자유롭게 적극적으로!! 활용할 것
5. 스터디
   깔끔하게 잘 정리하는 편이다. 계속 이렇게 진행하면 된다. 다른 팀에게 스터디 정리 페이지를 그대로 공유해줘도 도움 될 수 있도록 하는 것이 goal이다.. (나중에 찾아보기에 편한 것들 위주로 정리해도 좋고!!)
6. 컨셉 기획서
   지속적으로 바뀌는 사항에 대해서 업데이트를 잘 하고 있는 편이다. 다만, 수정/내용추가 등등의 표시를 일일이 하지 않아도 된다. 어차피 위키는 변경 내역이 따로 관리되기 때문에 최종 버전을 깔끔하게 유지하는 것이 더 좋다
7. 업데이트 노트
   이번주에는 굳이 이걸 안해도 되는데 연습 차원에서 먼저 해본 것이라면 잘했다. 다음주부터 릴리스가 있을때마다 이걸 작성하면 된다 (결국 따지고 보면 업데이트 노트는 완료된 이슈들의 집합이겠지..)

전체적으로 이 팀은 빠르게 안정화되고 있는 느낌이다. 전반적으로 매끄럽게 진행중인 것 같다. (+1)

**Comment by Jsfumato** [comment]
크으... 감사합니다 정진하겠슴다

**Comment by atgchan** [comment]
감사합니다 교수님~
