### ISSUE TITLE
재빌드 문제가 혹시 이 문제일수도... 

### ISSUE THREAD

**Issue by ujentus** [atgchan/2015_GaeKyungPu#38]
http://discuss.cocos2d-x.org/t/cocos-3-2-how-to-stop-visual-studio-rebuilding-entire-cocos-every-time/15687

PDB파일 생성안했거나, 바뀌었거나...

**Comment by ujentus** [comment]
내가 니들거 받아서 재현해봤는데... 이문제 맞는것 같다~~ 할때마다 빌드하길래 위에 옵션 바꿨더니 잘 됨..

**Comment by atgchan** [comment]
감사합니다 교수님! 저희도 잘 되요~ㅎㅎ
