### ISSUE TITLE
4-피드백 수정-TimeMap을 std::Array로 바꾸기

### ISSUE THREAD

**Issue by atgchan** [atgchan/2015_GaeKyungPu#53]
4-피드백 수정-TimeMap을 std::Array로 바꾸기

**Comment by Jsfumato** [comment]
일단 엉성하지만, 정해진 메모리 영역을 벗어나지 않도록, std::array를 이용하여 체크... 
강력히 수정 요망하지만 1차적으로 돌아는 간다
