### ISSUE TITLE
1-D GameScene piece의 회전 구현

### ISSUE THREAD

**Issue by Jsfumato** [atgchan/2015_GaeKyungPu#6]
GameScene에서 tile 클릭 시 다음 둘 중 하나의 행동
- addChild(게임 말)
- **rotate(게임 말)**
- sprite의 변경을 통한 게임 말(piece)의 회전 구현

**Comment by atgchan** [comment]
하드코딩으로 구현함!
2주차에서 병사를 객체화 하면 다시 수정해야 할 부분
