### ISSUE TITLE
7 - 죽을때 서서히 사라지게 만들기

### ISSUE THREAD

**Issue by seokmin** [atgchan/2015_GaeKyungPu#82]
죽는 놈은 서서히 사라진다.
완전히 사라질때 죽는 소리가 난다.

**Comment by Jsfumato** [comment]
서서히 사라지든 일단 해당 animation을 사용하는게 중요하지 않남!
일단 사라지는 animation 적용했고 서서히 사라지는건 시간여유나면 바로 넣겠슴
